//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EletronicProduct.java
//  @ Date : 2018-07-11
//  @ Author : 
//
//




public class EletronicProduct implements EletronicProduct, Eletronic
{
	private Object waves;
	public void Abc()
	{
	
	}
}
