# Generated by Django 2.1.3 on 2018-11-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bun', models.IntegerField(blank=True, null=True)),
                ('irum', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membertab',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=10)),
                ('reg_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'membertab',
                'managed': False,
            },
        ),
    ]
