# Generated by Django 2.1.3 on 2018-11-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('myno', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('regdate', models.DateTimeField()),
            ],
        ),
    ]
