# Generated by Django 2.1.3 on 2018-11-21 05:55

# 테이블 관련 테이블은 cmd 창에서
# python manage.py makemigrations 해준 후 model이 생기면, 
# python manage.py migrate 해주면 업데이트 됨.
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # Primary키를 따로 만들어주지 않으면 자동으로 생김.
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
